services:
  php:
    image: php:8.1-fpm
    container_name: php
    volumes:
      - ./php:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - backend

  node:
    image: node:22
    container_name: node
    volumes:
      - ./node:/home/node/app
    working_dir: /home/node/app
    command: npm start
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
