services:
  php:
    image: php:8.1-fpm
    container_name: php
    volumes:
      - ./backend:/var/www/html
    ports:
      - 9000:9000

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306

  node:
    image: node:22
    container_name: node
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - php

volumes:
  db-data:
